import { parseTint } from './layerLook';
import type {
  FlipbookLayer,
  FlipbookRecipe,
  FlipbookRecipeBank,
  FlipbookStrength,
} from './types';
import shippingRecipes from '../../../public/vfx/hit_ref_v1/recipes.json' with {
  type: 'json',
};

export const FLIPBOOK_STRENGTHS: FlipbookStrength[] = ['L', 'M', 'H'];

export const FLIPBOOK_STRENGTH_LABEL: Record<FlipbookStrength, string> = {
  L: '轻',
  M: '中',
  H: '重',
};

/** Aligns with vfx-ai-pipeline reference: 17 frames @30fps, FX from t=1. */
export const DEFAULT_FLIPBOOK_RECIPE: FlipbookRecipe = {
  id: 'hit_ref_v1_M',
  name: '命中参考 v1 · 中',
  strength: 'M',
  fps: 30,
  length: 29,
  layers: [
    {
      id: 'E3_ring_smoke',
      name: 'E3 圆环烟',
      enabled: true,
      z: 0,
      overCharacter: true,
      offsetX: 0,
      offsetY: 0,
      rotation: 0,
      randomRotation: false,
      randomRotationMinDeg: -15,
      randomRotationMaxDeg: 15,
      scale: 1,
      opacity: 0.42,
      brightness: 1.35,
      lift: 0.2,
      liftDark: 0,
      liftBright: 0,
      despill: 0.45,
      startFrame: 1,
      duration: 14,
      blend: 'screen',
      tint: '#ffffff',
    },
    {
      id: 'E4_wide_short_smoke',
      name: 'E4 宽短冲击烟',
      enabled: true,
      z: 1,
      overCharacter: true,
      offsetX: 0,
      offsetY: 0,
      rotation: 0,
      randomRotation: false,
      randomRotationMinDeg: -15,
      randomRotationMaxDeg: 15,
      scale: 1,
      opacity: 0.38,
      brightness: 1.4,
      lift: 0.22,
      liftDark: 0,
      liftBright: 0,
      despill: 0.5,
      startFrame: 1,
      duration: 14,
      blend: 'screen',
      tint: '#ffffff',
    },
    {
      id: 'E4b_wide_short_fiber_smoke',
      name: 'E4-b 宽短纤维烟',
      enabled: true,
      z: 1.05,
      overCharacter: true,
      offsetX: 0,
      offsetY: 0,
      rotation: 0,
      randomRotation: false,
      randomRotationMinDeg: -15,
      randomRotationMaxDeg: 15,
      scale: 1,
      opacity: 0.85,
      brightness: 1.2,
      lift: 0.15,
      liftDark: 0,
      liftBright: 0,
      despill: 0.4,
      startFrame: 1,
      duration: 14,
      blend: 'steam',
      tint: '#ffffff',
    },
    {
      id: 'E4c_wide_short_fiber_smoke',
      name: 'E4-c 宽短纤维烟',
      enabled: true,
      z: 1.1,
      overCharacter: true,
      offsetX: 0,
      offsetY: 0,
      rotation: 0,
      randomRotation: false,
      randomRotationMinDeg: -15,
      randomRotationMaxDeg: 15,
      scale: 1,
      opacity: 0.85,
      brightness: 1.2,
      lift: 0.15,
      liftDark: 0,
      liftBright: 0,
      despill: 0.4,
      startFrame: 1,
      duration: 18,
      blend: 'steam',
      tint: '#ffffff',
    },
    {
      id: 'E5_narrow_long_smoke',
      name: 'E5 窄长冲击烟',
      enabled: true,
      z: 2,
      overCharacter: true,
      offsetX: 0,
      offsetY: 0,
      rotation: 0,
      randomRotation: false,
      randomRotationMinDeg: -15,
      randomRotationMaxDeg: 15,
      scale: 1,
      opacity: 0.4,
      brightness: 1.35,
      lift: 0.18,
      liftDark: 0,
      liftBright: 0,
      despill: 0.45,
      startFrame: 1,
      duration: 14,
      blend: 'screen',
      tint: '#ffffff',
    },
    {
      id: 'E5b_narrow_long_fiber_smoke',
      name: 'E5-b 窄长纤维烟',
      enabled: true,
      z: 2.05,
      overCharacter: true,
      offsetX: 0,
      offsetY: 0,
      rotation: 0,
      randomRotation: false,
      randomRotationMinDeg: -15,
      randomRotationMaxDeg: 15,
      scale: 1,
      opacity: 0.85,
      brightness: 1.2,
      lift: 0.15,
      liftDark: 0,
      liftBright: 0,
      despill: 0.4,
      startFrame: 1,
      duration: 16,
      blend: 'steam',
      tint: '#ffffff',
    },
    {
      id: 'E5c_narrow_long_fiber_smoke',
      name: 'E5-c 窄长纤维烟',
      enabled: true,
      z: 2.1,
      overCharacter: true,
      offsetX: 0,
      offsetY: 0,
      rotation: 0,
      randomRotation: false,
      randomRotationMinDeg: -15,
      randomRotationMaxDeg: 15,
      scale: 1,
      opacity: 0.85,
      brightness: 1.2,
      lift: 0.15,
      liftDark: 0,
      liftBright: 0,
      despill: 0.4,
      startFrame: 1,
      duration: 28,
      blend: 'steam',
      tint: '#ffffff',
    },
    {
      id: 'E6_narrow_long_smoke_rtl',
      name: 'E6 反向窄长烟',
      enabled: true,
      z: 3,
      overCharacter: true,
      offsetX: 0,
      offsetY: 0,
      rotation: 0,
      randomRotation: false,
      randomRotationMinDeg: -15,
      randomRotationMaxDeg: 15,
      scale: 1,
      opacity: 0.4,
      brightness: 1.35,
      lift: 0.18,
      liftDark: 0,
      liftBright: 0,
      despill: 0.45,
      startFrame: 1,
      duration: 14,
      blend: 'screen',
      tint: '#ffffff',
    },
    {
      id: 'E6c_wide_short_fiber_smoke',
      name: 'E6-c 宽短纤维烟(向左)',
      enabled: true,
      z: 3.05,
      overCharacter: true,
      offsetX: 0,
      offsetY: 0,
      rotation: 0,
      randomRotation: false,
      randomRotationMinDeg: -15,
      randomRotationMaxDeg: 15,
      scale: 1,
      opacity: 0.85,
      brightness: 1.2,
      lift: 0.15,
      liftDark: 0,
      liftBright: 0,
      despill: 0.4,
      startFrame: 1,
      duration: 14,
      blend: 'steam',
      tint: '#ffffff',
    },
    {
      id: 'E7_sweat_spray',
      name: 'E7 飞汗',
      enabled: true,
      z: 4,
      overCharacter: true,
      offsetX: 0,
      offsetY: 0,
      rotation: 0,
      randomRotation: false,
      randomRotationMinDeg: -15,
      randomRotationMaxDeg: 15,
      scale: 1,
      opacity: 0.95,
      brightness: 1.1,
      lift: 0,
      liftDark: 0,
      liftBright: 0,
      despill: 0.25,
      startFrame: 1,
      duration: 16,
      blend: 'screen',
      tint: '#ffffff',
    },
    {
      id: 'E7b_sweat_scatter',
      name: 'E7-b 四散飞汗',
      enabled: true,
      z: 4.5,
      overCharacter: true,
      offsetX: 0,
      offsetY: 0,
      rotation: 0,
      randomRotation: false,
      randomRotationMinDeg: -15,
      randomRotationMaxDeg: 15,
      scale: 1,
      opacity: 0.95,
      brightness: 1.1,
      lift: 0,
      liftDark: 0,
      liftBright: 0,
      despill: 0.25,
      startFrame: 1,
      duration: 14,
      blend: 'screen',
      tint: '#ffffff',
    },
    {
      id: 'E7c_sweat_chunks',
      name: 'E7-c 块状飞汗',
      enabled: true,
      z: 4.6,
      overCharacter: true,
      offsetX: 0,
      offsetY: 0,
      rotation: 0,
      randomRotation: false,
      randomRotationMinDeg: -15,
      randomRotationMaxDeg: 15,
      scale: 1,
      opacity: 0.95,
      brightness: 1.1,
      lift: 0,
      liftDark: 0,
      liftBright: 0,
      despill: 0.25,
      startFrame: 1,
      duration: 16,
      blend: 'screen',
      tint: '#ffffff',
    },
    {
      id: 'E8b1_arc_smoke',
      name: 'E8-b1 弧状烟',
      enabled: true,
      z: 3.2,
      overCharacter: true,
      offsetX: 0,
      offsetY: 0,
      rotation: 0,
      randomRotation: false,
      randomRotationMinDeg: -15,
      randomRotationMaxDeg: 15,
      scale: 1,
      opacity: 0.85,
      brightness: 1.2,
      lift: 0.15,
      liftDark: 0,
      liftBright: 0,
      despill: 0.4,
      startFrame: 1,
      duration: 12,
      blend: 'screen',
      tint: '#ffffff',
    },
    {
      id: 'E8b2_arc_smoke',
      name: 'E8-b2 弧状烟(反向)',
      enabled: true,
      z: 3.25,
      overCharacter: true,
      offsetX: 0,
      offsetY: 0,
      rotation: 0,
      randomRotation: false,
      randomRotationMinDeg: -15,
      randomRotationMaxDeg: 15,
      scale: 1,
      opacity: 0.85,
      brightness: 1.2,
      lift: 0.15,
      liftDark: 0,
      liftBright: 0,
      despill: 0.4,
      startFrame: 1,
      duration: 12,
      blend: 'screen',
      tint: '#ffffff',
    },
    {
      id: 'E8c1_right_spread_smoke',
      name: 'E8-c1 向右扩散烟',
      enabled: true,
      z: 3.15,
      overCharacter: true,
      offsetX: 0,
      offsetY: 0,
      rotation: 0,
      randomRotation: false,
      randomRotationMinDeg: -15,
      randomRotationMaxDeg: 15,
      scale: 1,
      opacity: 0.85,
      brightness: 1.2,
      lift: 0.15,
      liftDark: 0,
      liftBright: 0,
      despill: 0.4,
      startFrame: 1,
      duration: 28,
      blend: 'steam',
      tint: '#ffffff',
    },
    {
      id: 'E8c2_right_spread_smoke',
      name: 'E8-c2 向右扩散烟',
      enabled: true,
      z: 3.12,
      overCharacter: true,
      offsetX: 0,
      offsetY: 0,
      rotation: 0,
      randomRotation: false,
      randomRotationMinDeg: -15,
      randomRotationMaxDeg: 15,
      scale: 1,
      opacity: 0.85,
      brightness: 1.2,
      lift: 0.15,
      liftDark: 0,
      liftBright: 0,
      despill: 0.4,
      startFrame: 1,
      duration: 28,
      blend: 'steam',
      tint: '#ffffff',
    },
    {
      id: 'E2_near_sparks',
      name: 'E2 近核火花',
      enabled: true,
      z: 5,
      overCharacter: true,
      offsetX: 0,
      offsetY: 0,
      rotation: 0,
      randomRotation: false,
      randomRotationMinDeg: -15,
      randomRotationMaxDeg: 15,
      scale: 1,
      opacity: 1,
      brightness: 1,
      lift: 0,
      liftDark: 0,
      liftBright: 0,
      despill: 0.35,
      startFrame: 1,
      duration: 10,
      blend: 'add',
      tint: '#ffffff',
    },
    {
      id: 'E2b_hit_sparks',
      name: 'E2-b 击中火星',
      enabled: true,
      z: 5.5,
      overCharacter: true,
      offsetX: 0,
      offsetY: 0,
      rotation: 0,
      randomRotation: false,
      randomRotationMinDeg: -15,
      randomRotationMaxDeg: 15,
      scale: 1,
      opacity: 1,
      brightness: 1,
      lift: 0,
      liftDark: 0,
      liftBright: 0,
      despill: 0.3,
      startFrame: 1,
      duration: 12,
      blend: 'add',
      tint: '#ffffff',
    },
    {
      id: 'E1_core_flash',
      name: 'E1 核心闪光',
      enabled: true,
      z: 6,
      overCharacter: true,
      offsetX: 0,
      offsetY: 0,
      rotation: 0,
      randomRotation: false,
      randomRotationMinDeg: -15,
      randomRotationMaxDeg: 15,
      scale: 1,
      opacity: 1,
      brightness: 1,
      lift: 0,
      liftDark: 0,
      liftBright: 0,
      despill: 0.35,
      startFrame: 1,
      duration: 10,
      blend: 'add',
      tint: '#ffffff',
    },
  ],
};

export function cloneRecipe(src: FlipbookRecipe): FlipbookRecipe {
  return {
    ...src,
    layers: src.layers.map((l) => ({ ...l })),
  };
}

export function recipeForStrength(
  src: FlipbookRecipe,
  strength: FlipbookStrength,
): FlipbookRecipe {
  const copy = cloneRecipe(src);
  copy.strength = strength;
  copy.id = `hit_ref_v1_${strength}`;
  copy.name = `命中参考 v1 · ${FLIPBOOK_STRENGTH_LABEL[strength]}`;
  return copy;
}

/**
 * Factory bank shipped in the Habby zip (editor L/M/H, not identical copies).
 * Source: app/public/vfx/hit_ref_v1/recipes.json
 */
function withLayerDefaults(layer: FlipbookLayer): FlipbookLayer {
  return {
    ...layer,
    overCharacter: layer.overCharacter !== false,
    rotation: Number.isFinite(layer.rotation) ? layer.rotation : 0,
    randomRotation: layer.randomRotation === true,
    randomRotationMinDeg: Number.isFinite(layer.randomRotationMinDeg)
      ? layer.randomRotationMinDeg
      : -15,
    randomRotationMaxDeg: Number.isFinite(layer.randomRotationMaxDeg)
      ? layer.randomRotationMaxDeg
      : 15,
    tint: parseTint(layer.tint),
    liftDark: Number.isFinite(layer.liftDark) ? Math.max(0, Math.min(12, layer.liftDark)) : 0,
    liftBright: Number.isFinite(layer.liftBright)
      ? Math.max(0, Math.min(2, layer.liftBright))
      : 0,
  };
}

export function defaultFlipbookBank(): FlipbookRecipeBank {
  // Shipping JSON may omit newer fields (e.g. overCharacter); normalize below.
  const rec = (shippingRecipes as unknown as { recipes?: FlipbookRecipeBank })
    .recipes;
  if (rec?.L && rec?.M && rec?.H) {
    return cloneBank({
      L: { ...rec.L, layers: rec.L.layers.map((l) => withLayerDefaults({ ...l })) },
      M: { ...rec.M, layers: rec.M.layers.map((l) => withLayerDefaults({ ...l })) },
      H: { ...rec.H, layers: rec.H.layers.map((l) => withLayerDefaults({ ...l })) },
    });
  }
  return {
    L: recipeForStrength(DEFAULT_FLIPBOOK_RECIPE, 'L'),
    M: cloneRecipe(DEFAULT_FLIPBOOK_RECIPE),
    H: recipeForStrength(DEFAULT_FLIPBOOK_RECIPE, 'H'),
  };
}

export function cloneBank(src: FlipbookRecipeBank): FlipbookRecipeBank {
  return {
    L: cloneRecipe(src.L),
    M: cloneRecipe(src.M),
    H: cloneRecipe(src.H),
  };
}

export function findLayer(
  recipe: FlipbookRecipe,
  id: string,
): FlipbookLayer | undefined {
  return recipe.layers.find((l) => l.id === id);
}
